name: build installer for support OS
on: push

jobs:
  build-app:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    name: Build the application
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 19
      - run: ./gradlew package
      - run: mkdir staging && cp app/build/installer/* staging
      - name: upload build result
        uses: actions/upload-artifact@v2
        with:
          name: iracing-parser-${{matrix.os}}
          path: staging